<?php defined('MW_PATH') || exit('No direct script access allowed');

/**
 * Translation file for "[[category]]" category.
 * 
 * This translation is automatically generated by the Translate extension.
 * 
 * @package Cyber Fision EMA
 * @author Serban George Cristian <cristian.serban@Cyber Fision.com>
 * @link http://www.CyberFision.com/
 * @copyright 2013-2016 Cyber Fision EMA (http://www.Cyber Fision.com)
 * @license http://www.CyberFision.com/license/
 * @since 1.1
 */
 
 